module.exports = {
  keywords: [''],
  age: 17,
  Developer: 'khir',
  name: 'khir salh',
  onStart: async function ({api,event,args,
  convertTime,defaultStderrClearLine,
    enableStderrClearLine,
getExtFromAttachmentType,
        getExtFromMimeType,
    getExtFromUrl,
    getPrefix,
    getTime,
    jsonStringifyColor,
    message,
    randomString,
    randomNumber,
    removeHomeDir,
    splitPage,
    translateAPI,
    downloadFile,
    findUid,
    getStreamsFromAttachment,
    translate,
    shortenURL,
getStreamFromURL,
  }) {
    
  },
};
